---
- hosts: localhost
  connection: local
  become: true 
  
  tasks:
    - name: Installing JDK 8
      yum: 
        name: java-1.8.0-openjdk
        state: latest
  
    - name: Create Deployment user
      group: name="sdc" system=yes

    - name: Create Deployment Group
      user: name="sdc" createhome=yes system=yes group="sdc"

    - name: Make Temporary Download Directory
      file: dest="/tmp/sdc" state=directory mode=755
 
    - name: Fetch Streamsets Tarball and Download
      get_url:
        url="http://archives.streamsets.com.s3.amazonaws.com/datacollector/3.22.1/tarball/streamsets-datacollector-common-3.22.1.tgz" 
        dest="/tmp/sdc/streamsets-datacollector-common-3.22.1.tgz"
      register: new_sdc_tarball
    
    - name: Create Installation Directory
      file: dest="/opt/streamsets-datacollector" state=directory mode=755 owner="sdc" group="sdc"
 
    - name: Extract Streamsets Tarball
      command: "tar -xf /tmp/sdc/streamsets-datacollector-common-3.22.1.tgz -C /opt/streamsets-datacollector/" 
 
        
 
    - name: Creating Startup Script for Streamsets 
      ansible.builtin.lineinfile: 
        path: /opt/streamsets-datacollector/streamsets-datacollector-3.22.1/bin/start.sh
        line: nohup ./streamsets dc </dev/null >/dev/null 2>&1 & 
        mode: '0777'
        create: yes
     
    - name: Changing Permissions Recursively
      ansible.builtin.file:
        path: /opt/streamsets-datacollector
        state: directory
        recurse: yes
        owner: sdc
        group: sdc
                
    - name: Starting Streamsets with SDC user
      become_user: sdc
      shell: nohup sh /opt/streamsets-datacollector/streamsets-datacollector-3.22.1/bin/streamsets dc &
      register: remote_tmp
      


